# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20171023_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='restapi.Product'),
        ),
    ]
