# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20171023_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restapi.Cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
