# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20171026_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restapi.Cart'),
        ),
    ]
