# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20171026_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
