# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_auto_20171026_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restapi.Product', unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerID',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
