# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20171026_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.AddField(
            model_name='customer',
            name='lastInitial',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
